# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-Screenshot
version:      1.00
version_from: Screenshot.pm
installdirs:  site
requires:
    Image::Magick:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
